apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-storage-deployment
  labels:
    app: block-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: block-storage
  template:
    metadata:
      labels:
        app: block-storage
    spec:
      containers:
        - name: block-storage
          image: docker.io/library/file-storage-app:v10
          ports:
            - containerPort: 80
          env:
            - name: FILE_STORAGE_SERVER_PORT
              value: "80"
            - name: FILE_STORAGE_PG_USER
              value: "postgres"
            - name: FILE_STORAGE_PG_PASSWORD
              value: "postgres"
            - name: FILE_STORAGE_PG_HOST
              value: "postgresdb-service"
            - name: FILE_STORAGE_PG_PORT
              value: "5432"
            - name: FILE_STORAGE_REDIS_HOST
              value: "redis-service"
            - name: FILE_STORAGE_REDIS_PORT
              value: "6379"
            - name: FILE_STORAGE_MINIO_HOSTS
              value: "minio-0-service:9000,minio-1-service:9000,minio-2-service:9000,minio-3-service:9000,minio-4-service:9000,minio-5-service:9000"
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message" ]
---
apiVersion: v1
kind: Service
metadata:
  name: block-storage-service
spec:
  type: NodePort
  selector:
    app: block-storage
  ports:
    - port: 80