apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-1
  labels:
    app: minio-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-1
  template:
    metadata:
      labels:
        app: minio-1
    spec:
      containers:
        - name: minio-1
          image: quay.io/minio/minio:latest
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9090
          volumeMounts:
            - mountPath: /data
              name: minio-1-volume
      volumes:
        - name: minio-1-volume
          hostPath:
            path: /data/minio1/data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: minio-1-service
spec:
  type: NodePort
  selector:
    app: minio-1
  ports:
    - port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-1-admin-service
spec:
  type: NodePort
  selector:
    app: minio-1
  ports:
    - port: 9090