apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-3
  labels:
    app: minio-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-3
  template:
    metadata:
      labels:
        app: minio-3
    spec:
      containers:
        - name: minio-3
          image: quay.io/minio/minio:latest
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9090
          volumeMounts:
            - mountPath: /data
              name: minio-3-volume
      volumes:
        - name: minio-3-volume
          hostPath:
            path: /data/minio3/data
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: minio-3-service
spec:
  type: NodePort
  selector:
    app: minio-3
  ports:
    - port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-3-admin-service
spec:
  type: NodePort
  selector:
    app: minio-3
  ports:
    - port: 9090